name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Deploy to ZEIT Now
      run: |
        npm install
        npm run test
      env:
        LNCT_BASE_URL: ${{ secrets.LNCT_BASE_URL }}
        LNCTU_BASE_URL: ${{ secrets.LNCTU_BASE_URL }}
        ACCSOFT_ID: ${{ secrets.ACCSOFT_ID }}
        PASSWORD: ${{ secrets.PASSWORD }}
